server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  jpa:
    show-sql: true
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
management:
  endpoints:
    web:
      exposure:
        # open monitor points
        include: '*'
  endpoint:
    health:
      # show health status all the time
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true